### PR TITLE
Designed new agent window

### PR DESCRIPTION
**Pull request by FabriceIRANKUNDA**
#185

### CODE REVIEW

**Comment by michaelsharpe** [comment]
Awesome! For some of these design issues, could you post a screenshot here on the ticket @FabriceIRANKUNDA ?

**Comment by FabriceIRANKUNDA** [comment]
> Awesome! For some of these design issues, could you post a screenshot here on the ticket @FabriceIRANKUNDA ?

I know there are still things to improve but this is the current status
https://user-images.githubusercontent.com/58092199/221376158-9211305b-ec19-40ac-9268-401437e701c0.mp4

**Comment by FabriceIRANKUNDA** [comment]
there are still things to improve for better UX but this is the current status

https://user-images.githubusercontent.com/58092199/221376470-045801d0-c53c-46f1-a245-6a672839b845.mp4

**Comment by lalalune** [comment]
This looks great, we're just missing the Discord connectors

**Comment by lalalune** [comment]
@FabriceIRANKUNDA I have updated to organize the agents correctly

- Each agent has a root spell and a name
- Each agent has multiple connects, Discord is just one of them
- Each connect adds in data which will be combined into the agent.data
- Name should be editable

From here, we should just need to:
- Fix the update, delete, export
- Add import
- Make sure enabled/disabled work
- On delete, clear the agent view
- Store the latest state of the agent window so the user returning will see the same agent (can fetch again though)

**Comment by lalalune** [comment]
Screenshot 2023-02-25 at 4 24 02 PM

**Pull request closed without merging**
