### PR TITLE
Remove unused sqlite vss extension.

### PR DESCRIPTION
**Pull request by fire**
## What Changed:

Remove unused sqlite vss extension.

Fixes:

1. https://github.com/Oneirocom/Magick/security/code-scanning/4
2. https://github.com/Oneirocom/Magick/security/code-scanning/3
3. https://github.com/Oneirocom/Magick/security/code-scanning/2
4. https://github.com/Oneirocom/Magick/security/code-scanning/1

## How to test:

Test that nothing broke.

### CODE REVIEW

**Comment by Knar33** [comment]
The lib/constants file is referenced in a few places
image

**Comment by fire** [comment]
So keep the constants but delete the dlls?

**Comment by fire** [comment]
@Knar33 updated

**Review by Knar33 — APPROVED** [review]
Magick still compiles and runs. These are files for MacOS/iOS so I think it's safe to remove.

**Pull request merged**
