### PR TITLE
ID based key for spells

### LINKED ISSUE #186: Spells should have IDs, use ID as key instead of name
Right now if two users with different project IDs on the same database try to make a spell with the same name it will fail.

- Spells should have a UUID identifier which is their key. Each spell's UUID is unique.
- There should only be one spell with any given name for each projectId.
- There can be many spells with different names with the same projectId

### LINKED ISSUE #223: Rename Subspell Broken
The patch is attempting to save the spell by spell-name, however it needs to be saved by the spell's ID instead and sent along with the config's projectId.

Screenshot 2023-02-22 at 9 24 42 PM

### PR DESCRIPTION
**Pull request by sshivaditya2019**
- Updated the schema to use UUID as the primary key,
- Created URI using UUID and Name, after creating new.
- The `tab.id` is now same as UUID of the active spell
- `tab.name` will have the URI
- LocalState is filtered based on the UUID now.

Fixes #186 

- Rename is also fixed (Possibly Fixes #223 )

### CODE REVIEW

**Comment by lalalune** [comment]
Looks very close, a few notes
- spellName and name are confused, maybe we rename spellName to spellId everywhere?
- "Rename spell" - should pass the existing name as default
- "Save as" spell has the spell's UUID in the form field and doesn't work

**Comment by sshivaditya2019** [comment]
Potential Issues

- `spell-runner` not updating with latest spell-name,  does not affect execution.
- Error in Engine Context, Spellref does not point to the correct active spell. (Observed only after renaming)

**Comment by sshivaditya2019** [comment]
Changes

- spellName has been removed
- URI is read from the route
- URI is stored in `tab.URI`
- URI is UUID + Base64Encoded(Spell Name)

**Comment by lalalune** [comment]
> Potential Issues
> spell-runner not updating with latest spell-name, does not affect execution.
> Error in Engine Context, Spellref does not point to the correct active spell. (Observed only after renaming)

Hmm, yeah, maybe @michaelsharpe can take a look at the new branch for this, `spell-uuid`

Merged with diff save, that's good.

Rename and save as work. Save as errors after performing the operation and updating.

Importing is not working.

**Pull request merged**
