### PR TITLE
improved event ui to meet figma design

### PR DESCRIPTION
**Pull request by FabriceIRANKUNDA**
## What Changed:

- Added select event
- Delete selected events
- UI fixes

## How to test:

- Visit event window

## Additional information:

Any other information that might be useful while reviewing.

### CODE REVIEW

**Review by Knar33 — APPROVED** [review]
Multi select + delete works, and it lets me select events across multiple pages and delete them.
The text is a lot more readable now.
Delete selected button cannot be clicked with none selected

**Comment by Knar33** [comment]
FYI this new page has the same issue as #904 has

**Comment by lalalune** [comment]
We will need to resolve sorting in a separate PR, it's a complex issue.

**Comment by lalalune** [comment]
I'm going to merge this in since it's a lot better than what we have now

**Pull request merged**
