### PR TITLE
Process Discord [leave,join,user voice presence,get text channel, get voice channel] commands

### LINKED ISSUE #366: [Discord Plugin] Add "list channels", "list voice channels", "join voice channel" and "leave voice channel" node
We want to be able to "decide" to write in a channel or join a channel. Right now it's hardcoded like `join <channel name>` and its not good. If the AI can decide to join or leave based on a language prompt we can build complex autonomous behavior and natural interaction around this.

- [ ] List Discord Text Channels
- [ ] List Discord Voice Channels
- [ ] Join Voice Channel (channel name, server)
- [ ] Leave voice channel

Agents can only be in one voice channel at once, most likely!

### PR DESCRIPTION
**Pull request by sshivaditya2019**
- [x] Discord Voice Channel Leave and Join commands added
- [x] Bot joins channel, based on the users's voice status
- [x] Get Text Channels and Voice Channels 

Fixes #366 

### What was changed

The discord commands were hard for example, the prompt from the user had to start with join for the bot to join the voice channel, now when a user enters a random prompt `let's talk hop on the vc`, the bot will join the voice channel, of which the message's author was part of.

These actions are to be used with AgentExecutor. This node builds the model, which will have the tokenized tool description. AgentExecutor must have 3 tools at any time for it work.  This Node will predict the tool to be used, and assign a score to it.

#### Tools Added

- List Voice Channels
- List Text Channels
- Join Voice Channel
- Leave Voice Channel

### How to test

Since, we don't have any node level tests right now, this can be tested using a sample spell. For any case, where the AgentExecutor node feels there is no action to be done, it returns the same as the output. For any other case it should return the tool output. All the discord errors are handled within the `discord.ts` and `discord-voice.ts` files.

### CODE REVIEW

**Comment by lalalune** [comment]
Great. @sshivaditya2019 can you please indicate
- What was changed
- How to test
We have a new engineer starting who will be doing QA on PRs, so we need to inform him of how to test this

**Comment by sshivaditya2019** [comment]
### What was changed

The discord commands were hard for example, the prompt from the user had to start with join for the bot to join the voice channel, now when a user enters a random prompt `let's talk hop on the vc`, the bot will join the voice channel, of which the message's author was part of.

These actions are to be used with AgentExecutor. This node builds the model, which will have the tokenized tool description. AgentExecutor must have 3 tools at any time for it work.  This Node will predict the tool to be used, and assign a score to it.

### How to test

Since, we don't have any node level tests right now, this can be tested using a sample spell. For any case, where the AgentExecutor node feels there is no action to be done, it returns the same as the output. For any other case it should return the tool output. All the discord errors are handled within the `discord.ts` and `discord-voice.ts` files.

**Comment by Knar33** [comment]
I'm testing this now. I got an error when the bot joins a voice channel about not having the module "node-opus". I had to manually install the "node-opus" package to get past the error. This also happens in the current Development branch.

**Comment by sshivaditya2019** [comment]
node-opus is a deprecated library, it has been replaced by @discord/opus.  Discord should not require node-opus, this could be local error too, node-opus was part of the package.json. I'll try to replicate the error in my dev environment

**Comment by Knar33** [comment]
I tested using this setup, not 100% sure I'm using it correctly though, and I'm not sure what the voice/text channel tools are for.
image

It joins the voice channel I'm in when I input "join" and many other variations like "hop in vc", and it outputs the text "joined {voice channel name}" in the text channel associated with the voice channel. If I tell it to join when I'm not in a channel it sends "The action result is You need to be in a voice channel to talk to the bot!" to the output worker, and doesn't join a voice channel.

It leaves the voice channel when I input "leave" and the other variations listed in the keywords, and it outputs the text "leaving {channel where I issued the command}". Not sure if this output matters but it's technically wrong, it should probably output "leaving {voice channel name}" if anything.

when I input a command like "list voice" or "list text" it calls an output worker with the input containing a list of the appropriate channels. I couldn't get it to spit out the channel list in discord chat but I can see it in my logs. 

I wanted to try some less obvious inputs to try the "weighting". If I just say "Voice" or "VC" it always executes "leave voice channel" even if it's not in a voice channel. If I input a text that's not on any of the keyword lists it sends 'NO ACTION TO BE TAKEN' to the output worker.

**Comment by sshivaditya2019** [comment]
The voice and text channel tools were part of the original ticket #366. Regarding the dependency, I was not able to replicate the node-opus issue (Dev environment: Ubuntu 22.04, Node 19).

The issue with list voice and list text should be solved by adding an echo node after the Agent Executor. Also, the reason for `VC` or `Voice` commands being tagged under the `Leave Voice Channel node` is because of the underlying algorithm. BM25 is predominantly a ranking algorithm that uses the frequency of tokens in ranking the document. `Leave VC node` has several occurrences of the term `VC` or `Voice`.

**Comment by Knar33** [comment]
I just pulled it again and didn't have the node-opus dependency issue, strange.

I tested using the spell you gave me and everything worked. The only thing that seems wrong is that it says it's leaving the text channel where you entered the text command.

**Comment by sshivaditya2019** [comment]
Fixed that, it should output the voice channel name now.

**Review by Knar33 — APPROVED** [review]

**Pull request merged**
