### PR TITLE
Xstate Plugin

### PR DESCRIPTION
**Pull request by fire**
## What Changed:

* Copied the github plugin as the xstate plugin

## How to test:

Make sure the xstate plugin can take a json object for state, [SAMPLE] json schema and a sample text input. It should output `true` as an json object.

1. Xstate test

```json
{
  "id": "promise",
  "initial": "pending",
  "states": {
    "pending": {
      "on": {
        "RESOLVE": { "target": "resolved" },
        "REJECT": { "target": "rejected" }
      }
    },
    "resolved": {},
    "rejected": {}
  }
}
```

2. Event 

```
RESOLVE
```

3. Context

```json
{}
```

4. Output

```
resolved
```

## Additional information:

Any other information that might be useful while reviewing.

### CODE REVIEW

**Comment by fire** [comment]
Wrap up.

1. Use objects rather than json strings.
2. Find a different category than "flow"
3. Don't bother with feature flagging.
4.

**Comment by fire** [comment]
Some changes to the magick architecture broke this. Fixing.

**Comment by fire** [comment]
This is ready for review.

**Comment by michaelsharpe** [comment]
@benbot any word on this PR for state stuff?

**Comment by coffeeorgreentea** [comment]
@fire can you please share an example spells with a couple use cases?

**Comment by fire** [comment]
I'll quickly write some spells.

**Pull request closed without merging**
