### PR TITLE
Remove chat options from the text generation node.

### PR DESCRIPTION
**Pull request by fire**
Was causing developers to get caught on a confusing error.

### CODE REVIEW

**Comment by lalalune** [comment]
The most popular models, like 99% of what people use, is ChatGPT and GPT-4, which are the chat models, so we need to fix this :'D

**Comment by coffeeorgreentea** [comment]
> The most popular models, like 99% of what people use, is ChatGPT and GPT-4, which are the chat models, so we need to fix this :'D

going to take a look into and try to fix rather then merge this.
@fire what exactly is the error?

**Comment by fire** [comment]
I think it does not output. As far as I know chatgpt4 is not open to api usage. Not sure about gpt3.

**Comment by lalalune** [comment]
> I think it does not output. As far as I know chatgpt4 is not open to api usage generally. Not sure about gpt3.

We all have GPT4, ChatGPT is open to all, it's 1/10th the cost of Davinci / GPT 3 so it's what almost all of our users use, and what we need to offer by default.

**Pull request closed without merging**
