### PR TITLE
Node ux improvements

### PR DESCRIPTION
**Pull request by michaelsharpe**
## What Changed:

- restyled nodes
- Improved node selection highlight
- improved connection lines
  - unselected - medium thickness
  - select node - node connections appear bolder and glow
- added connection glow
- sockets get larger on hover
- connections connected to hovered socket highlight
- you can deselect nodes now by clicking on the editor
- modified styling of comments
- added our brand font Berkely mono as a remote font resource (can't check into repo due to licensing)

## How to test:

- Ensure nodes still turn green/red on run
- select a node and follow its connections
- hover over sockets to highlight a connection
- select a node and click on the editor area of deselect again

## Additional information:

- There are a few known bugs
  - when the connection is horizontal it disappears
  - the glow appears to be cut off at a bounding box around the connections
  - if you select a node and hover over its socket, the connection stops being high-lighted
- I suspect the first two bugs are related, and the SVG view box needs to be modified somehow.  I am not great with svg so figured I would submit this now and if someone else gets to it before me, awesome.
-

### CODE REVIEW

**Comment by Knar33** [comment]
It seems like I'm not getting the horizontal node bug
image

**Comment by Knar33** [comment]
The alignment of comments seems off, the text is covered by one of the nodes (not really a big deal because you can just move the nodes)
image

**Comment by lalalune** [comment]
> The alignment of comments seems off, the text is covered by one of the nodes (not really a big deal because you can just move the nodes) image

I believe this is preexisting

**Review by FabriceIRANKUNDA — COMMENTED** [review]
Screenshot 2023-06-07 at 10 30 19

Changing the value of --glow has affected some styling i.e active tab and switch buttons should have our primary color

Screenshot 2023-06-07 at 10 32 47

When the node title is too long it is colliding with the node id, it would be great when node can be resizable if possible

**Review by coffeeorgreentea — APPROVED** [review]

**Pull request merged**
