### PR TITLE
Add contributors

### PR DESCRIPTION
**Pull request by fire**
## What Changed:

Add coffeeorgreentea as contributor

- [x] @fire 
- [x] @FabriceIRANKUNDA 
- [x] ~~add yourself~~

Add yourself using the files changed website editor.

## How to test:

How can the reviewer test your changes and validate that they work as described?

Check if everyone from the development team is here.

### CODE REVIEW

**Comment by fire** [comment]
We need to use the all contributor github app.

**Comment by lalalune** [comment]
@fire we have it and its set up

**Comment by lalalune** [comment]
@all-contributors please add @FabriceIRANKUNDA for code

**Comment by lalalune** [comment]
@all-contributors please add @fire for code

**Comment by lalalune** [comment]
@all-contributors please add @coffeeorgreentea for code

**Comment by fire** [comment]
https://github.com/all-contributors please add @benbot for code

**Comment by fire** [comment]
@all-contributors please add @benbot for code

**Comment by fire** [comment]
Closing due to the bot being active.

**Pull request closed without merging**
