### PR TITLE
Fixed multiple loading screen when more than one tab are opened

### PR DESCRIPTION
**Pull request by FabriceIRANKUNDA**
## What Changed:
when loading the spell, show the loading screen only on the active tab

## How to test:

- Open multiple spells and try to refresh the page, you might not see it with fast internet.

## Additional information:

Any other information that might be useful while reviewing.

### CODE REVIEW

**Comment by Knar33** [comment]
Is this referring to browser tabs or spell tabs? i tried replicating the bug on development and couldn't get it to  happen. I had spells open on two tabs, and refreshing one didn't cause a loading screen on the other (even when I had my internet throttled to 3g speeds).

**Comment by FabriceIRANKUNDA** [comment]
https://github.com/Oneirocom/Magick/assets/58092199/08ae5f05-54d0-444d-9593-a86a5f3807e7

**Comment by Knar33** [comment]
> Screen.Recording.2023-05-10.at.17.32.08.mov

I was able to reproduce the bug on development (using 6x cpu slowdown) but I am not getting any loading .gif when I try it on this branch. Is it supposed to be showing a single loading gif?

**Comment by Knar33** [comment]
> > Screen.Recording.2023-05-10.at.17.32.08.mov
> 
> I was able to reproduce the bug on development (using 6x cpu slowdown) but I am not getting any loading .gif when I try it on this branch. Is it supposed to be showing a single loading gif?

I looked into this and the loadingScreen component is there but the svg just never triggers the onLoad event that changes its visibility to visible. That component works elsewhere on the page just fine, so I think it's just a timing issue (the spell loads before the svg does).

**Review by Knar33 — APPROVED** [review]

**Pull request merged**
