### PR TITLE
Feat: Added Script to convert documentation to embedding

### LINKED ISSUE #758: Script to generate vectors and upload all documentation to database
We want to vectorize our documentation, put it into the database as a document store and make this is a somewhat repeatable process.

- [ ] Parse generated markdown from docusaurus
- [ ] Break into vectorizable chunks
- [ ] Run through embeddings model
- [ ] Store Data and embeddings in documents table

- [ ] Add caching -- Hash the markdown and check if the hash already exists in the database -- if the hashes are the same then the document hasn't changed, and we shouldn't re-upload. Otherwise delete old and vectorize new

This should be formatted in such a way that it could be added to our CI/CD and only runs AI services when new text is added. However, just being able to run it *occasionally* is plenty to complete the task for now, and we'll break CI/CD for auto-documentation into a separate task.

### PR DESCRIPTION
**Pull request by sshivaditya2019**
## What Changed:

Created a script to convert the docasuarus documents into vectors. This can be used with GetDocument Node to fetch relevant document files, which can then be sent to a new node, DocumentToContent, this node can join the content of all the retrieved documents.

## How to test:

`node scripts/doc-embed.js`

## Additional information:

This script requires `OPEN_AI_KEY ` and `DATABASE_URL` in `.env` and `.env.local`

Fixes #758

### CODE REVIEW

**Comment by sshivaditya2019** [comment]
It is `node scripts/doc-embed.js` and not `node script/doc-embed.js`

**Comment by Knar33** [comment]
I'm getting another error, looks like you hard coded the path to your markdown files on line 163

`findMarkdownFiles('/home/sshivaditya/Projects/MagickML/apps/docs/docs/api/classes/')`

**Comment by Knar33** [comment]
I replaced your file path with my own and I'm getting a 401 error. It is sending `Authorization: 'Bearer: undefined'`

**Comment by Knar33** [comment]
Seems like the script was looking for OPENAI_API_KEY (not OPEN_AI_KEY). The script worked when I set that, testing the new node now.

**Comment by Knar33** [comment]
Seems like the rest is working. The script created a bunch of embeddings and when I use Get Documents it returns the most relevant documents first. The new node successfully combines the content of my documents array into a single string.

**Pull request merged**
